config/routes.rb
TinyExample::Application.routes.draw do

  resources :users
  resources :sessions

  namespace :analysis do
    resources :trade, :only => :index
  end

  get "welcome/index"

  match "/login" => "sessions#new"
  match "/logout" => "sessions#destroy" 

  root :to => 'analysis/trade#index'

end

app/models/ability.rb
# encoding: UTF-8
class Ability
  include CanCan::Ability

  def initialize(user)
  	# alias_action :index, :show, :to => :read
    # alias_action :new, :to => :create
    # alias_action :edit, :to => :update

    if user.is?(:manager)
    	can :manage, :all
    end

    if user.is?(:member)
      can :read, Auction::Trade
    end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/auction/trade.rb
#该model对应244服务器上data_ihaveu_com_development中的auction_trade，在config/initializers/multi_dataset中配置了IhaveuRecord
class Auction::Trade < IhaveuRecord
  self.table_name = 'auction_trades'


  # 按条件统计某年有过成功订单的用户信息（id，name，最近成功订单id，最近成功订单日期）
  #
  # wangyang.shen 2013.09.05
  def self.find_success_trade_users(year)
    sql = <<-SQL
      SELECT user_id , au.name as user_name, trade_id, trade_created_at
      FROM  (
              SELECT t.user_id as user_id, t.id as trade_id, t.created_at as trade_created_at
              FROM auction_trades AS t
              INNER JOIN auction_trades_updatings AS tu
              ON tu.trade_id = t.id and tu.status='receive'
              WHERE t.delivery_service is NOT NULL AND t.delivery_service!= ''
              AND t.status in ('complete','receive') AND YEAR(t.created_at) = #{year}
              ORDER BY t.id DESC 
            ) AS c
      LEFT JOIN auction_users AS au ON au.id = c.user_id
      GROUP BY c.user_id
    SQL
    self.find_by_sql(sql)
  end

  # 发送用户信息邮件方法
  #
  # wangyang.shen 2013.09.06
  def self.send_info_mail
    year = 2013
    results = self.find_success_trade_users(year)
    # 出现错误抛出异常，防止出现无效邮箱导致发送邮件失败
    begin
      Notifier.send_info_mail(User.all,results).deliver if User.all.present? && results.present?
    rescue Exception => e
      puts e.message
    end
  end
end

app/models/user.rb
#encoding: utf-8
class User < ActiveRecord::Base
  attr_accessible :id, :name, :email, :role
  cattr_accessor :current_user

  ROLES = [
    ['普通用户', 'member'],
    ['管理员', 'manager']
  ]

  #判断用户是否是role角色
  # == params ===
  # role(String):: 角色名
  #
  # == return ===
  # true/false
  #
  # zhanghong
  # 2012-07-11
  def is?(role)
    self.role == role.to_s
  end

  private
  # 查找用户表中是否有目标用户，并验证公司邮箱密码
  # === Params ====
  # email(string)，password(string)
  # ===  Return ===
  # 用户 or nil
  # 
  # ping.wang  2013.08.23
  def self.check_user(email, password)
    return nil if !email
    user = where(:email => email).first
    user && sign_up(email, password) ? user : nil
  end

  # 验证公司邮箱和密码是否匹配
  # === Params ====
  # email(string)，password(string)
  # ===  Return ===
  # Boolean
  # 
  # ping.wang 2013.08.23
  def self.sign_up(email, password)
    return nil if !email
    ldap = Net::LDAP.new
    ldap.host = "mail.ihaveu.net"
    ldap.port = 389
    ldap.auth "uid=#{email},ou=people,dc=ihaveu,dc=net", "#{password}"
    ldap.bind
  end
end

app/controllers/analysis/trade_controller.rb
class Analysis::TradeController < ApplicationController
	
	# / GET
	def index
		@year = 2013
		@results = Auction::Trade.find_success_trade_users(@year).paginate :page => params[:page]
	end
end

app/controllers/application_controller.rb
#encoding: utf-8
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :login_check

  before_filter do |c|
    p "---"*30
    User.current_user = User.find(c.session[:id]) unless c.session[:id].nil?
  end

  #cancan插件用户权限验证失败处理方法
  #
  # zhanghong
  # 2012-07-11
  rescue_from CanCan::AccessDenied do |exception|
    flash[:notice] = "对不起，你没有权限进行该操作！"
    redirect_to(root_path)
  end

  # 登陆验证方法, 如果未登陆，记住当前访问地址
  # 
  # ping.wang
  # 2013.08.23
  def login_check
    if session[:id].blank? # 记住登录前访问的路径
      session[:back_path] = request.fullpath unless request.format.json?
      redirect_to("/login") and return
    end
  end
private
  def current_ability
    begin
      @current_user = @current_user || User.current_user || User.find(session[:id])
      @current_ability ||= Ability.new(@current_user)
    rescue
      redirect_to("/login") and return
    end
  end
end

app/controllers/sessions_controller.rb
#encoding: utf-8
class SessionsController < ApplicationController
	skip_before_filter :login_check

  layout 'sessions'

  # 登陆方法
  # 
  # ping.wang
  def create
    if Rails.env == "production"
      @user = User.check_user(params[:email],params[:password])
    else
      @user = check_user(params[:email],params[:password])
    end

    if @user.present?
      # 跳转到登录前访问的页面
      back_path = session[:back_path]
      back_path = "/" if back_path.blank? || back_path =~ /login/
      session[:back_path] = nil

      set_session and redirect_to(back_path)
    else
      redirect_to("/login" ,:notice => "用户名或密码错误，请重新登陆")
    end
  end

  def destroy
    reset_session
    redirect_to("/login")
  end

  protected
  # 查找数据库中是否有目标用户
  #
  # ping.wang
  def check_user(email, password)
    return nil unless email.present?
    user = User.find_by_email(email)
    user.present? ? user : nil
  end

  # 设置session
  #
  # ping.wang
  def set_session
    %w(id email name role).each {|i| session[i.to_sym] = @user[i] if @user[i].present? }
  end
end

app/controllers/users_controller.rb
#encoding: utf-8
class UsersController < ApplicationController
  load_and_authorize_resource  :class => "User"

  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: '成功创建用户' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: '成功修改资料' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # 转换时间显示格式
  def shown_time(cur_time)
    if cur_time.is_a?(Time)
      cur_time.strftime("%Y-%m-%d %H:%M")
    else
      ""
    end
  end

  # 转换时间显示格式
  def shown_date(cur_time)
    if cur_time.is_a?(Time)
      cur_time.strftime("%Y-%m-%d")
    else
      ""
    end
  end


  def role_str(role)
    str = User::ROLES.find{ |i| i.last == role }
    str.present? ? str.first : ""
  end
end

app/views/analysis/trade/index.html.erb
<% content_for :head do %>
   订单用户信息
<% end %>

<div>
  <header>
    <h3><%= @year %>年有过成功订单的用户信息</h3>
  </header>

  <div>
    <% if @results.present? %>
    <table class="table table-bordered table-hover">
      <tr>
        <th>用户ID</th>
        <th>姓名</th>
        <th>最近成功订单ID</th>
        <th>最近成功订单日期</th>
      </tr>
      <% @results.each do|result| %>
         <tr>
           <td><%= result["user_id"] %></td>
           <td><%= result["user_name"] %></td>
           <td><%= link_to result["trade_id"], "http://#{SITE_DOMAIN_CMS}/auction/manage/trades/#{result['trade_id']}", :target => "_blank" %></td>
           <td><%= shown_date(result["trade_created_at"]) %></td>
         </tr>
      <% end %>
    </table>
        <%= will_paginate @results, :previous_label=> '上一页', :next_label=> '下一页' %>
    <% else %>
      <p class="muted">没有相关用户！</p>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:head) || "TinyExample" %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
		<div class="navbar-inner">
			<div class="container" style="width: 940px;">
				<a class="brand" href="/">TinyExample</a>
				<div class="nav-collapse subnav-collapse">
			    <ul id="system_menu" class="nav nav-pills large-font-size">
            <li><a href="/analysis/trade">订单用户</a></li>
			    </ul>

				  <ul class="nav pull-right">
            <%- if session[:id].present? -%>
              <li>
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= session[:name] %>
                  <b class="caret" style="border-top-color: #595959;border-bottom-color: #595959;"></b>
                </a>
                <ul class="dropdown-menu" style="min-width: 120px;">
                  <% if can?(:read, User) %>
                    <li><a href="/users">用户列表</a></li>
                    <li class="divider"></li>
                  <% end %>
                  <li><a href="/logout">退出</a></li>
                </ul>
              </li>
            <% end %>
				  </ul>
				</div>
			</div>
		</div>
	</div>

  <div class="container" style="margin-top:60px;min-height:760px;">
      <%- if flash[:notice].present? -%>
        <div class="warning"><%=raw flash[:notice] %></div>
      <%- end -%>
      <%= yield %>   
    </div>
  </div>

  <div class="clear"></div>
  <footer class="footer">
    <div class="container" style="margin-top: 110px;">
      <p align="center">Powered by 基因团队 © 2013</p>
    </div>
  </footer>
</body>
</html>

app/views/layouts/sessions.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TinyExample</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div>
    <%- if flash[:notice].present? -%>
      <div class="warning"><%=raw flash[:notice] %></div>
    <%- end -%>
    <%= yield %>   
  </div>

</body>
</html>

app/views/notifier/send_info_mail.html.erb
<div style="font-size: large;">
  <p>您好，</p>
  <p>以下是2013年有过成功订单的用户信息:</p>
</div>

<div>
  <table style="font-size: large;width: 60%;">
    <tr style="height: 40px;">
      <th style="padding: 8px;
              text-align: left;
              vertical-align: inherit;
              border-top: 1px solid #DDD;
              border-left: 1px solid #DDD;">用户ID</th>
      <th style="padding: 8px;
              text-align: left;
              vertical-align: inherit;
              border-top: 1px solid #DDD;
              border-left: 1px solid #DDD;">姓名</th>
      <th style="padding: 8px;
              text-align: left;
              vertical-align: inherit;
              border-top: 1px solid #DDD;
              border-left: 1px solid #DDD;">最近成功订单ID</th>
      <th style="padding: 8px;
              text-align: center;
              vertical-align: inherit;
              border-top: 1px solid #DDD;
              border-left: 1px solid #DDD;
              border-right: 1px solid #DDD;">最近成功订单日期</th>
    </tr>
    <% @results.first(20).each do|result| %>
        <tr style="height: 30px;">
          <td style="text-align: left;
                  padding: 8px;
                  line-height: 40px;
                  vertical-align: inherit;
                  border-top: 1px solid #DDD;
                  border-left: 1px solid #DDD;"><%= result["user_id"] %></td>
          <td style="text-align: left;
                  padding: 8px;
                  line-height: 40px;
                  vertical-align: inherit;
                  border-top: 1px solid #DDD;
                  border-left: 1px solid #DDD;"><%= result["user_name"] %></td>
          <td style="text-align: left;
                  padding: 8px;
                  line-height: 40px;
                  vertical-align: inherit;
                  border-top: 1px solid #DDD;
                  border-left: 1px solid #DDD;"><%= link_to result["trade_id"], "http://#{SITE_DOMAIN_CMS}/auction/manage/trades/#{result['trade_id']}",:style => "text-decoration:none;", :target => "_blank" %></td>
          <td style="text-align: center;
                  padding: 8px;
                  line-height: 40px;
                  vertical-align: inherit;
                  border-top: 1px solid #DDD;
                  border-left: 1px solid #DDD;
                  border-right: 1px solid #DDD;"><%= result["trade_created_at"].strftime("%Y-%m-%d") %></td>
        </tr>
    <% end %>
    <tr>
      <td colspan="4" style="vertical-align: top;
              border-top: 1px solid #DDD;">
      </td>
    </tr>
  </table>
  <% if @results.size > 20 %>
      <p style="color: #999999;">只显示前20条记录</p>
  <% end %>
  <br/>
  <a style="text-decoration:none" href="http://<%= SITE_DOMAIN %>/analysis/trade">点击这里, 查看详细信息！</a>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :姓名 %>
    <%= f.text_field :name, :class => "span3" %>
  </div>
  <div class="field">
    <%= f.label :邮箱 %>
    <div class="input-append"><%= f.text_field :email,:class => "span2" %><span class="add-on">@ihaveu.net</span></div>
  </div>
  <div class="field">
    <%= f.label :角色 %>
    <div class="input-append">
      <%= f.select(:role, User::ROLES, {}, {:class => "span3"})%>
    </div>
  </div>
  <br/>
  <div class="actions">
    <%= f.submit "确定", :class => "btn"%>
  </div>
<% end %>

app/views/users/edit.html.erb
<% content_for :head do %>
  修改用户 | TinyExample
<% end %>

<h2 class="header">修改用户</h2>

<%= render 'form' %>

<%= link_to '详情', @user %> |
<%= link_to '返回', users_path %>

app/views/users/index.html.erb
<% content_for :head do %>
  用户列表 | TinyExample
<% end %>

<h2 class="header">用户列表</h2>

<table class="table table-bordered table-hover">
  <tr>
    <th>ID</th>
    <th>姓名</th>
    <th>邮箱</th>
    <th>角色</th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= link_to user.id, user_path(user) %></td>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= role_str(user.role) %></td>
    <td style="text-align:right;">
      <%= link_to '修改', edit_user_path(user), :class=> "btn btn-info" %>
      <%= link_to '删除', user, method: :delete, data: { confirm: '确定删除？' }, :class=> "btn btn-danger"%>
    </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to '添加用户', new_user_path %>

app/views/users/new.html.erb
<% content_for :head do %>
  添加用户 | TinyExample
<% end %>

<h2 class="header">添加用户</h2>

<%= render 'form' %>

<%= link_to '返回', users_path %>

app/views/users/show.html.erb
<% content_for :head do %>
  添加用户 | TinyExample
<% end %>

<h2 class="header">用户信息</h2>

<dl id="user_info" class="dl-horizontal">
  <dt>ID</dt>
  <dd><%= @user.id %></dd>
  <dt>姓名</dt>
  <dd><%= @user.name %></dd>
  <dt>邮箱</dt>
  <dd><%= @user.email %></dd>
</dl>

<%= link_to '修改', edit_user_path(@user) %> |
<%= link_to '返回', users_path %>

app/views/welcome/index.html.erb
<% content_for :head do %>
 	欢迎来到TinyExample | TinyExample
<% end %>

<h1>Hello, world!</h1>